config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :pockets
  resources :reports
  resources :teachers
  resources :exams
  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  
  def new #untuk menampilkan form data baru
    @exam = Exam.new
  end  
    
  def create #untuk memperoses data baru yang dimasukkan di form new
    exam = Exam.new (resources_params)
    exam.save 
    redirect_to exams_path
    flash[:notice] = 'Exam has been created'
  end  
    
  def edit #menampilkan data yang sudah disimpan
    @exam = Exam.find(params[:id])
  end 

  def update #melakukan proses ketika user mengedit data
    @exam = Exam.find(params[:id])
    @exam.update(resources_params)
    flash[:notice] = 'Exam has been update'
    redirect_to exams_path(@exam)
  end  

  def destroy #untuk menghapus data
    @exam = Exam.find(params[:id])
    @exam.destroy
    flash[:notice] = 'Exam has been destroy'
    redirect_to exams_path(@exam)
  end 

  def index #menampilkan seluruh data yang ada di database
    @exams = Exam.all
  end 

  def show #menampilkan  sebuah data sectemplateara detail
      id = params[:id]
      @exam = Exam.find(id)
      # render plain: id
      # render plain: @book.title 
     end

    private 

  def resources_params
    params.required(:exam).permit(:title, :mapel, :duration, :nilai, :status, :level, :student_id)
  end
  end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/edit.html.erb
<%= form_for (@exam) do |f| %>
      
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>
  
    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>
    
    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>
    
    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>
   
    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>
    
    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br>
    
    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>
    
    <%= f.submit %>
 <% end %>

app/views/exams/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container"><table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Title</th>
        <th>Mapel</th>
        <th>Duration</th>
        <th>Nilai</th>
        <th>Status</th>
        <th>Level</th>
        <th>Student_id</th>
        <th>Action</th>
    </tr>
    </thead>    <tbody>
    <% @exams.each do |exam| %>
    <tr>
        <td><%= exam.title %></td>
        <td><%= exam.mapel %></td>
        <td><%= exam.duration %></td>
        <td><%= exam.nilai %></td>
        <td><%= exam.status %></td>
        <td><%= exam.level %></td>
        <td><%= exam.student_id %></td>
        <td>
        <%= link_to 'Detail', exam_path(exam), class:"btn btn-outline-secondary" %> 
        <%= link_to 'Edit', edit_exam_path(exam), class:"btn btn-outline-warning" %> 
        <%= link_to 'Delete', exam_path(exam) , method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %>
        </td>    </tr>
    <% end %>
    </tbody></table> 
<%= link_to 'New Exam', new_exam_path(), class:"btn btn-primary" %><!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
</div>

app/views/exams/new.html.erb
<%= form_for (@exam) do |f| %>
      
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>
  
    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>
    
    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>
    
    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>
   
    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>
    
    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br>
    
    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>
    
    <%= f.submit %>
 <% end %>

app/views/exams/show.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

Title: <%= @exam.title %> </br>
Mapel: <%= @exam.mapel %> </br>
Duration: <%= @exam.duration %> </br>
Nilai: <%= @exam.nilai %> </br>
Status: <%= @exam.status %> </br>
Level: <%= @exam.level %> </br>
Student_id: <%= @exam.student_id %> </br>